### ISSUE TITLE
Question: is crewAI a good choice for an email classifier?

### ISSUE THREAD

**Issue by younes-io** [joaomdmoura/crewAI#100]
I want to build a customer emails classifier, and I'd like to know if `crewAI` could be leveraged for such a use case. I'd appreciate having your ideas on how it could be used / optimized for this use case. BTW, the LLM is Azure OpenAI API.

**Comment by PiotrEsse** [comment]
I wonder if CrewAI is especially good for this. 

Should using simple agent with custom tool be sufficient? 
Why to use CrewAI for this? 

I am thinking about this too. Parse IMAP folders, store messages with metadata in database, classify them and put to respective folders and do some additional actions.

**Comment by younes-io** [comment]
@PiotrEsse : I started experimenting.. there are a few challenges, because of the nature of classification and GPT models, but overall, I think `crewAI` could be used to come up with a system for such a problem.
However, for now, `crewAI` doesn't support parallel processing (for agents), only sequential workflows are supported.

**Comment by joaomdmoura** [comment]
Yeah I think you could do something exceptional with it! And there are tools to connect to gmail already on langchain you could use! 😎👉👉 
I'll look if I can put together an example of this!
Parallel processing is in the roadmap #167

**Comment by devorbitus** [comment]
FYI: relevant example of email processing https://github.com/joaomdmoura/crewAI-examples/tree/main/CrewAI-LangGraph
