### ISSUE TITLE
Support for Azure OpenAI

### ISSUE THREAD

**Issue by vansen** [joaomdmoura/crewAI#101]
Hello, thanks for this really helpful project! I am using Azure OpenAI over OpenAI itself and I would like to know if there is already a way to do that (Usually the baseurl needs to be set) or if that support is planned to be added?
Thank you!

**Comment by llxxxll** [comment]
Perhaps this is possible? The code is untested. CrawAI can use APIs based on langchain models.
```python
import os

from langchain.schema import HumanMessage
from langchain_openai import AzureChatOpenAI

os.environ["AZURE_OPENAI_API_KEY"] = "..."
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://<your-endpoint>.openai.azure.com/"

Azure_model = AzureChatOpenAI(
    openai_api_version="2023-05-15",
    azure_deployment="your-deployment-name",
)


researcher = Agent(
  role='Researcher',
  goal='Discover new insights',
  backstory="...",
  verbose=True,
  llm = Azure_model
```

**Comment by younes-io** [comment]
I've taken this example from the wiki and adjusted it for Azure as well:

```python
import os
from crewai import Agent, Task, Crew, Process
from langchain.agents import load_tools

from langchain.chat_models.azure_openai import AzureChatOpenAI

llm = AzureChatOpenAI(
    model=model_name,
    api_version=openai_api_version,
    api_key=openai_api_key,
    # azure_endpoint=open_ai_base,    
    base_url=open_ai_base,    
)

# Loading Human Tools
human_tools = load_tools(["human"])

# Define your agents with roles and goals
researcher = Agent(
  role='Senior Research Analyst',
  goal='Uncover cutting-edge developments in AI and data science in',
  backstory="""You are a Senior Research Analyst at a leading tech think tank.
  Your expertise lies in identifying emerging trends and technologies in AI and
  data science. You have a knack for dissecting complex data and presenting
  actionable insights.""",
  verbose=True,
  allow_delegation=False,
  # Passing human tools to the agent
  llm=llm,
  tools=human_tools
)
# the rest of the code...
```

**Comment by sorin-costea** [comment]
Azure changed to regional endpoints so might be that's why the above stopped working?
Now it's like https://your_region.api.cognitive.microsoft.com/openai/deployments/your_deployment/chat/completions?api-version=some_version_string

**Comment by BodapatiNirupamasai** [comment]
I am trying to run the below code but somehow I am getting " Error code: 401 - {'error': {'message': 'Incorrect API key provided"
Could anyone help me with this?

from crewai import Agent
from textwrap import dedent
from tools import yt_tool
from load_dotenv import load_dotenv
from langchain_openai import AzureChatOpenAI
import os

load_dotenv()


llm = AzureChatOpenAI(
    azure_deployment="gpt-4", 
    api_version="2023-06-01-preview",  
    api_key=os.environ.get("key"),
    azure_endpoint=os.environ.get("endpoint"),
)


researchAgent = Agent(
                    role='Research Analsyt for Youtube Videos',
                    goal='Search popular youtube videos to extract actionable insights for the topic {topic}',
                    tools=[yt_tool],
                    llm=llm,
                    verbose= True,
                    memory=True,
                    allow_delegation=True,
                    backstory=dedent("""You're a Research Analsyt at a large company.
                                        list 5 popular youtube videos on the {topic} as you're responsible for analyzing content in the youtube videos, 
                                        providing insights and suggestions to the business."""),
)

**Comment by BodapatiNirupamasai** [comment]
> sorin
I am not able to connect to crew Ai using Azure Open AI key.

**Comment by sorin-costea** [comment]
Could be because of the same Azure endpoint format upgrade I have? See
discussion here (LiteLLM is the underlying connection):
https://github.com/BerriAI/litellm/discussions/5995

**Comment by amishkhatri** [comment]
> I am trying to run the below code but somehow I am getting " Error code: 401 - {'error': {'message': 'Incorrect API key provided" Could anyone help me with this?
> 
> from crewai import Agent from textwrap import dedent from tools import yt_tool from load_dotenv import load_dotenv from langchain_openai import AzureChatOpenAI import os
> 
> load_dotenv()
> 
> llm = AzureChatOpenAI( azure_deployment="gpt-4", api_version="2023-06-01-preview", api_key=os.environ.get("key"), azure_endpoint=os.environ.get("endpoint"), )
> 
> researchAgent = Agent( role='Research Analsyt for Youtube Videos', goal='Search popular youtube videos to extract actionable insights for the topic {topic}', tools=[yt_tool], llm=llm, verbose= True, memory=True, allow_delegation=True, backstory=dedent("""You're a Research Analsyt at a large company. list 5 popular youtube videos on the {topic} as you're responsible for analyzing content in the youtube videos, providing insights and suggestions to the business."""), )

**Comment by amishkhatri** [comment]
You should setup environment variables in the system as AZURE_OPENAI_API_KEY
AZURE_OPENAI_ENDPOINT with the valid key and endpoint
Further,  initialize the object as 
llm = AzureChatOpenAI(
    azure_deployment="azure/<deployment_name>",
    api_version="<api_version>",
    temperature=<temprature 0-1 in numbers>
    )
You dont need to mention key and endpoint in the code anymore. 
Remember you should have deployment as "azure/<dep. name>" otherwise it wont work.

**Comment by thl456** [comment]
I have this same issue. Tried to change os.environ with codes below but doesn't work either. When I publish my app to Streamlit, the llm seems to still be calling OpenAI, I get the error message 'Incorrect API key provided............You can find your API key at https://platform.openai.com/account/api-keys....'

os.environ["AZURE_OPENAI_API_KEY"] = [my Azure API key]
os.environ["AZURE_OPENAI_ENDPOINT"] =[my Azure endpoint]

llm = AzureChatOpenAI(
    model = model,
    api_key = api_key, 
    api_version = api_version, 
    azure_endpoint = api_base)
