### ISSUE TITLE
Support for LangChain `0.1.0`

### ISSUE THREAD

**Issue by younes-io** [joaomdmoura/crewAI#102]
I got this when I upgraded LangChain

```
Installing collected packages: langchain
  Attempting uninstall: langchain
    Found existing installation: langchain 0.0.354
    Uninstalling langchain-0.0.354:
      Successfully uninstalled langchain-0.0.354
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
crewai 0.1.24 requires langchain<0.0.355,>=0.0.354, but you have langchain 0.1.0 which is incompatible.
Successfully installed langchain-0.1.0

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
```

**Comment by greysonlalonde** [comment]
@joaomdmoura Is there anything blocking a bump to `langchain 0.1.0` ? I can upgrade this today if not

**Comment by SeaDude** [comment]
Please consider using vanilla Python to avoid these types of `langchain` dependency issues.

**Comment by greysonlalonde** [comment]
@SeaDude this is not feasible for a variety of reasons - however, I want to clarify that there is no dependency issue with `langchain` as the supported versions are clearly specified in the [pyproject.toml](https://github.com/joaomdmoura/crewAI/blob/4f22bbf4d4b886e95bd3bbd4b35b8e49171bad72/pyproject.toml#L21) file.
