### ISSUE TITLE
Create multiple crews?

### ISSUE THREAD

**Issue by mattian7** [joaomdmoura/crewAI#107]
If I want to use `crew()` to create multiple crew, how does new crew receive previous outcome from the last crew? An example would be appreciate.

Here is the reason I have this issue: In a series of cases, the workflow of a job is not always pipeline. One task/crew may need to use the experience from at least 2 previous tasks/crews (in a parallel  way). Consider that the tasks can only be solved in a serial way in one crew, I have to create multiple crew.

**Comment by okoliechykwuka** [comment]
I think the Landing Page example in crewAI-examples demonstrates that.

check it out https://github.com/joaomdmoura/crewAI-examples/tree/main/landing_page_generator

**Comment by joaomdmoura** [comment]
Exactly what @okoliechykwuka you should be able to create multiple ones and pass the outcome of one into the other.
You can also pass the outcome of individual tasks, as those are available at `task.output` if you want to.

**Comment by Akki-droid** [comment]
@joaomdmoura Do we have option to create multiple crews, and invoke them separately (at different time) based on requirement.

This is the usecase
- I want to have crew running solution A and crew running solution B
- When i pass run ( solution A), it should want to kickoff crew running solution A
- When i pass run ( solution B), it should want to kickoff crew running solution B
