### ISSUE TITLE
Any advanced examples? (Landing pages, product, academic paper)

### ISSUE THREAD

**Issue by barshag** [joaomdmoura/crewAI#11]
(That are not using Replit, just pure locally with openhermes style....)

**Comment by joaomdmoura** [comment]
I've pushed the replay example to GitHub as well just in case: https://github.com/joaomdmoura/crewAI-examples

I'm working on a fully local example that I'll share next week using ollama 🔥

**Comment by joaomdmoura** [comment]
New full local example was added https://github.com/joaomdmoura/crewAI-examples/tree/main/instagram_post
