### ISSUE TITLE
LM Studio Integration via OpenAI API V1 using base URL

### ISSUE THREAD

**Issue by CraigRichards** [joaomdmoura/crewAI#115]
Have you considered LM Studio Integration?

Essentially it can spin up a local API with your model of choice which is compatible with OpenAI V1 API.

The main difference is that you would need to expose a config parameter for the OpenAI Base Url.

Thanks for the consideration and amazing project you have.

**Comment by greysonlalonde** [comment]
Hi @CraigRichards -  if you only need to tweak the OpenAI Base URL, you can do so like this : 


```python3
from langchain_openai import ChatOpenAI

ChatOpenAI(openai_base_url="http://localhost:1234/v1", openai_api_key="foo")
```

or with an env var:


```zsh
export OPENAI_API_BASE=http://localhost:1234/v1
```

Cheers!

**Comment by CraigRichards** [comment]
Thanks mate,
I tried asking the chatbot about base url's and it did not know anything about it.

Thanks for a quick reply and sorry if I missed this in your documentation.

Om shanti shanti shanti

**Comment by Zirgite** [comment]
It does not work at all.

**Comment by kobykotiv** [comment]
this does not work. I keep getting a connection error.

**Comment by Zirgite** [comment]
> this does not work. I keep getting a connection error.

I have found a solution but it is another thread:
https://github.com/joaomdmoura/crewAI/issues/154#issuecomment-1919150315

**Comment by Moses2917** [comment]
I got this to work without the need for langchain just using the base CrewAI and LM Studio

```python
from crewai import Agent, LLM, Task, Crew
llm = LLM(
    model='openai/qwen2.5-7b-instruct-q8_0-00001-of-00003',
    api_key="NA",
    base_url="http://127.0.0.1:1234/v1/"
)

agent = Agent(
    role='Customized LLM Expert',
    goal='Provide tailored responses',
    backstory="An AI assistant with custom LLM settings.",
    llm=llm
)

# Define your task
task = Task(
    description="Generate a list of 5 interesting ideas for an article, then write one captivating paragraph for each idea that showcases the potential of a full article on this topic. Return the list of ideas with their paragraphs and your notes.",
    expected_output="5 bullet points, each with a paragraph and accompanying notes.",
    agent = agent
)

the_boys = Crew(
    tasks=[task],
    agents=[agent],
).kickoff()

print(the_boys)
```
