### ISSUE TITLE
Isue with the Crew Ai instalation. Multidict package problem.

### ISSUE THREAD

**Issue by Ignaciol0** [joaomdmoura/crewAI#118]
Hello I was searching in the issues for a resolved issue about this and since I didn't find any here is mine.
Doing the pip installation of the crewai package I had a problem.
` ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects`

The research I have done told me that the problem was from either the pip or the Microsoft Visual C++ Build Tools.
I upgraded the pip and downloaded the Microsoft Building Tools from the link the error gave me.
Rebooted the computer and still the error persisted although with the pip upgrade there were some new thing that downloaded.
One possibility I saw that could have caused the problem is that I am using python 3.12.1 and I should use a lower version if that's the case. What version should I use? And if it's not the case any ideas what is causing the issue?

**Comment by greysonlalonde** [comment]
Hi @Ignaciol0 - I wasn't able to replicate with python 3.12.1 on M3 with `0.1.24`. Are you installing the latest version?

**Comment by greysonlalonde** [comment]
@Ignaciol0 see [this issue](https://github.com/imartinez/privateGPT/issues/1083)

**Comment by Ignaciol0** [comment]
Ok Sorry stupid mistake I downloaded the Build Tools but not the C++ part.

**Comment by parthjrana01** [comment]
@Ignaciol0 I faced the same problem. Did you get the solution

**Comment by Ignaciol0** [comment]
@parthjrana01 My particular Isue is that I downloaded the build tools but in the build tools there is a C++ part that I didn´t download.
