### ISSUE TITLE
Agent Request Throttling

### ISSUE THREAD

**Issue by greysonlalonde** [joaomdmoura/crewAI#119]
@joaomdmoura API throttling per agent is frequently mentioned in issues. Is there space on the roadmap to address this, and if so, mind if I start on it?

**Comment by mindwellsolutions** [comment]
@greysonlalonde This would be amazing! Having a 2 simple variables when defining the agent would work well:

**completed_successful_requests_perminute** = 59  # This will track how many API Requests have been completed
**tokens_processed_perminute** = 500 # If possible, the ability to limit the amount of tokens it will process in per minute or per task.

**Comment by joaomdmoura** [comment]
Done, merged in main, will cut a new version tomorrow and add docs
