### ISSUE TITLE
Issue when installing using pip in a virtual env

### ISSUE THREAD

**Issue by sumitbindra** [joaomdmoura/crewAI#121]
I tried installing crewai using pip in my virtual env created using venv. and got the following error. Any suggestions?

![image](https://github.com/joaomdmoura/crewAI/assets/25441198/f4010fc9-a9da-47a1-9d1c-3ea73fb992fb)

**Comment by JimJim12** [comment]
What version of python are you running in that environment? need some more details.

**Comment by greysonlalonde** [comment]
Solved in [this issue](https://github.com/joaomdmoura/crewAI/issues/118)

**Comment by Oriel-Barroso** [comment]
The error in that is solved in 121, is not the same as here

**Comment by greysonlalonde** [comment]
@Oriel-Barroso No, the exception is identical - the traceback above is shortened.
