### ISSUE TITLE
Issues with Pydantic dependencies

### ISSUE THREAD

**Issue by knotsandties** [joaomdmoura/crewAI#130]
After facing no problems running crewai, facing the following error:

> ImportError: cannot import name 'InstanceOf' from 'pydantic' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/init.cpython-311-darwin.so)

Tried uninstall-reinstall both crewai and pydantic. Any suggestions?

**Comment by Haripritamreddy** [comment]
What versions are you using both for crewai and pydantic?

**Comment by knotsandties** [comment]
For crewai: 
> Version: 0.1.24
For pydantic:
> Version: 2.5.3
Although, for compatibility I have also down-dated to 2.4.2 and have the same issues.

**Comment by knotsandties** [comment]
Figured out the issue: two versions of python running, required upgrading pydantic using:

`pip3 install --upgrade pydantic==2.4.2`

**Comment by boxinqb** [comment]
upgrading pydantic solves the issue for me too

`Successfully installed pydantic-2.4.2 pydantic-core-2.10.1`
