### ISSUE TITLE
duckduckgo rate limit error

### ISSUE THREAD

**Issue by scottiesan** [joaomdmoura/crewAI#136]
I am getting this running the example code

Traceback (most recent call last):
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 48, in _get_url
    raise RateLimitException(f"_get_url() {url} RateLimitError: resp.status_code==202")
duckduckgo_search.exceptions.RateLimitException: _get_url() https://links.duckduckgo.com/d.js RateLimitError: resp.status_code==202

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/CrewAI/app.py", line 72, in <module>
    result = crew.kickoff()
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/crew.py", line 127, in kickoff
    return self._sequential_loop()
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/crew.py", line 134, in _sequential_loop
    task_output = task.execute(task_output)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/task.py", line 56, in execute
    result = self.agent.execute_task(
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/agent.py", line 146, in execute_task
    result = self.agent_executor.invoke(
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/agents/executor.py", line 59, in _call
    next_step_output = self._take_next_step(
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 1055, in _take_next_step
    [
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 1055, in <listcomp>
    [
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/crewai/agents/executor.py", line 191, in _iter_next_step
    observation = tool.run(
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_core/tools.py", line 365, in run
    raise e
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_core/tools.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_community/tools/ddg_search/tool.py", line 39, in _run
    return self.api_wrapper.run(query)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_community/utilities/duckduckgo_search.py", line 81, in run
    results = self._ddgs_text(query)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_community/utilities/duckduckgo_search.py", line 57, in _ddgs_text
    return [r for r in ddgs_gen]
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/langchain_community/utilities/duckduckgo_search.py", line 57, in <listcomp>
    return [r for r in ddgs_gen]
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 103, in text
    for i, result in enumerate(results, start=1):
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 154, in _text_api
    resp = self._get_url("GET", "https://links.duckduckgo.com/d.js", params=payload)
  File "/Users/scott/miniconda3/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 57, in _get_url
    raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).__name__}: {ex}")
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://links.duckduckgo.com/d.js RateLimitException: _get_url() https://links.duckduckgo.com/d.js RateLimitError: resp.status_code==202
(base) scott@Scotts-MBP CrewAI %

**Comment by scottiesan** [comment]
my installation had some conflicts.  is resolved.

**Comment by alsonliplus** [comment]
Hello, I also encountered a similar problem, how did you solve it?
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com DuckDuckGoSearchException: Ratelimit

**Comment by abe-kenichi** [comment]
I also encountered it, and resolved it with "%pip install --upgrade --quiet  duckduckgo-search"

**Comment by KhaldiDataPanda** [comment]
> I also encountered it, and resolved it with "%pip install --upgrade --quiet duckduckgo-search"

Thanks , it solved it for me too, still idk what was the issue in 1st place (i installed the library after your thread so even fresh installations comes with the problem i guess)

**Comment by gyanendrarawat** [comment]
i cant 

> I also encountered it, and resolved it with "%pip install --upgrade --quiet duckduckgo-search"

doesnt resolve for me

**Comment by SoulEvill** [comment]
following on this thread... it was fine before but today i got this rate limit issue too. and upgrade doesnt solve my issue

**Comment by TsabarM** [comment]
following too.

**Comment by tholonia** [comment]
Confirming broken here as well (duckduckgo_search=5.3.1, crewai=0.30.0, crewai-tools=0.2.5)

```
> Entering new CrewAgentExecutor chain...
 Thought: I will start by conducting a broad search for information about epigenetics
Action: duckduckgo_search
Action Input: {"query": "epigenetics"} 

I encountered an error while trying to use the tool. This was the error: https://links.duckduckgo.com/d.js?q=epigenetics&kl=wt-wt&l=wt-wt&p=&s=0&df=y&vqd=4-277907738189382025553254121005238630619&ex=-1 202 Ratelimit.
 Tool duckduckgo_search accepts these inputs: A wrapper around DuckDuckGo Search. Useful for when you need to answer questions about current events. Input should be a search query.

```
Then it dropped to a different search (Serper?), but the weird thing is, the other search too uses `search_query` rather than `query`, but for some reason, some crew internal seems to be escaping the "_", resulting in `search\_query`, which then results in this failure:

```
 Thought: I will use another tool to search for information about epigenetics
Action: Search in a specific website
Action Input: {"website": "researchgate.net", "search\_query": "epigenetics"} 

I encountered an error while trying to use the tool. This was the error: WebsiteSearchTool._run() missing 1 required positional argument: 'search_query'.
 Tool Search in a specific website accepts these inputs: Search in a specific website(search_query: 'string', website: 'string') - A tool that can be used to semantic search a query from a specific URL content.

```

**Comment by joaomdmoura** [comment]
Hey folks, the rate limit unfortunately is imposed on the duck duck go side, we add a new exa tools that does offer free credits: https://github.com/joaomdmoura/crewAI-tools/tree/main/crewai_tools/tools/exa_tools
I'd recommend trying it out as well. Serper also offer a few free credits iirc and we have a tool for that,

**Comment by danielgen** [comment]
The weird thing is that this is not a rate limit problem: e.g.
```
  File "/opt/miniconda3/envs/crew/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 124, in _aget_url
    raise RatelimitException(f"{resp.url} {resp.status_code} Ratelimit")
duckduckgo_search.exceptions.RatelimitException: https://links.duckduckgo.com/d.js?q=teletubbies&kl=wt-wt&l=wt-wt&p=&s=0&df=y&vqd=4-23477882074055204179171254865267777697&ex=-1 202 Ratelimit
```

the link being returned contains results, so duckduckgo did execute the request. 
I tried inspecting duckduckgo_search_async.py, line 124 but so far no luck. 
Anyhow 202 is "the request has been accepted for processing, but the processing has not been finished yet"
I would expect 429 for rate limit problems... 

In any case I think this needs to be raised with langchain not crewai

**Comment by sclayturner** [comment]
Following this Issue: https://github.com/deedy5/duckduckgo_search/issues/215

Updating to prescribed version is currently working for me: `pip install -U duckduckgo_search==5.3.1b1`

**Comment by ad71** [comment]
@sclayturner that fixed it for me, thanks

**Comment by sameer1604** [comment]
@sclayturner Fixed it for me as well! Thank you

**Comment by 1WorldCapture** [comment]
`pip install --upgrade --quiet duckduckgo-search` saved me

**Comment by TsabarM** [comment]
I'm still getting connection timeout error. "https://duckduckgo.com ConnectTimeout: "
I'm running a loop for small amount of records to search. it get stuck at the few first records. 
` for item in tqdm(list_of_search, desc='searching main url'):
        try:
            url = DDGS().text(item , max_results=1)[0].get('href')
            main_url = get_main_parsed_url(url)
        except Exception as e:
            print(e)
            url = None
            main_url = None
        results_dict[item] = {'url': url, 'main_url': main_url}`

**Comment by gyanendrarawat** [comment]
`raise TimeoutException(f"{url} {type(ex).__name__}: {ex}") from ex duckduckgo_search.exceptions.TimeoutException: https://links.duckduckgo.com/d.js ReadTimeout:    `
 This time getting the above error, any fixes??

**Comment by dave-16** [comment]
from what i can think 1, you should set max_execution_time also when looping make shure you are requesting like with time cycle

**Comment by tomkat-cr** [comment]
> I also encountered it, and resolved it with "%pip install --upgrade --quiet duckduckgo-search"

`pip install --upgrade --quiet duckduckgo-search` finally resolves it for me. Ty

**Comment by faegan** [comment]
Still having this issue;

`pip install -U duckduckgo_search==5.3.1b1`

nor

`pip install --upgrade --quiet duckduckgo-search`

Resolved the issue.

**Comment by aymeric-roucher** [comment]
Just for anyone asking the question: this error is due to a rate limitation. This duckduckgo search service is free, so it's limited by the provider to a specific amount of requests per unit of time.

So the block is on the server side, not on your (client) side : **upgrading your packages will have no effect**! For those who feel like upgrading resolved the error, it's probably just that you waited one day and your rate limit was reset, so you could request again.

**Comment by Fluorurine** [comment]
Yeah same problem here. Still doesn't figure out Rate Limit. Hope someone come with a insight of this.

**Comment by AssetDK** [comment]
I do not have a solution for this, but this may be the explanation: https://duckduckgo.com/duckduckgo-help-pages/aichat/usage-limits/ 

That is, if you use a "strong" VPN connection - say from inside your firewall - DuckDuckGo will not know your ip and that may be blocked to stop DOS like search loops?

**Comment by deedy5** [comment]
update to the latest version

**Comment by amansingh9097** [comment]
version **duckduckgo-search==8.0.5** is still buggy, gets into rate limit exactly after 2 attempts each have 5 search results in each
