### ISSUE TITLE
Optional Agents in Tasks (mismatch documentation vs code)

### ISSUE THREAD

**Issue by michaelwdombek** [joaomdmoura/crewAI#142]
Hello  @ all,

First and foremost, I want to express my appreciation for this fantastic project! :)

I recently encountered an issue that was previously discussed in #71 , and I've spent some time examining both the code and the wiki. If I understand correctly, the tasks should function properly even when no agent is selected for a particular task. You can find more information about this in the [Wiki Reference to tasks](https://github.com/joaomdmoura/crewAI/wiki/Defining-Tasks#properties-of-a-task). However, based on my investigation into the code, it appears that this feature may not be currently implemented. Is there someone actively working on this feature, or has it been dropped?

I appreciate your clarification on this matter.

**Comment by joaomdmoura** [comment]
Great catch, indeed, right now the sequential process expects the tasks to be assigned, in other processes that wont be necessary, I've updated the wiki as part of that for now
