### ISSUE TITLE
`i18n.py` docstrings

### ISSUE THREAD

**Issue by matsuobasho** [joaomdmoura/crewAI#152]
https://github.com/joaomdmoura/crewAI/blob/main/src/crewai/utilities/i18n.py needs docstrings.  I can perhaps try tackling this once I get a handle on what's going on, so help appreciated.  I understand it's about internationalization settings (based on the description in `agent.py`), but that's about it in terms of my understanding.

**Comment by joaomdmoura** [comment]
Good point, this class is basically responsible for translation, it allow you to run your crew using a given language.
It does that by loading a translation json file into memory and then using it to set the prompts along the way.
