### ISSUE TITLE
Using GPT-4 instead 3.5

### ISSUE THREAD

**Issue by yuri12344** [joaomdmoura/crewAI#153]
Hi, I just setup 3 workers, with 3 tasks, and set to work with gpt 3.5-turbo, and instead use 3.5 he used 4.

**Comment by sirajperson** [comment]
You can set the GPT version by using LangChains OpenAI object:

```python
from langchain.chat_models import ChatOpenAI
from crewai import Agent

llm = ChatOpenAI(model='gpt-3.5-turbo') # Loading GPT-3.5-turbo

agent = Agent(
    **idea_analyst_config,
    verbose=True,
    llm=llm, # <----- passing our llm reference here
    tools=[
        SearchTools.search_internet,
        BrowserTools.scrape_and_summarize_kwebsite
    ]
)
```

**Comment by andybrandt** [comment]
Is it possible to use a specified pre-trained model or an [assistant ](https://platform.openai.com/docs/assistants/overview) previously defined using OpenAI's playground UI?

**Comment by joaomdmoura** [comment]
Not assistant yet, but soon, but yes you can use both local finetune models or other closed models as well
