### ISSUE TITLE
How to call the crew from a web app?

### ISSUE THREAD

**Issue by arjunkrishna** [joaomdmoura/crewAI#156]
How to call the crew from a web app, so that users can interact with it. If I missed some documentation anywhere, I apologize in advance.

**Comment by ikequan** [comment]
@arjunkrishna, you can use Python Flask and Celery task queueing.
workflow:
1. User sends request to flask route.
2. Within route def, queue the crew ai code with celery and return celery task id to the user
3. Use task id  to check progress of crewai, 
4. return final result from crewai to user.

**Comment by arjunkrishna** [comment]
found one sample - https://github.com/kno2gether/crewai-examples/blob/main/stock_analysis/main.py

**Comment by arjunkrishna** [comment]
thanks for the reply.
