### ISSUE TITLE
I get an error when model is got-3.5-tubo

### ISSUE THREAD

**Issue by rawmean** [joaomdmoura/crewAI#16]
I keep getting `Do I need to use a tool? No Invalid Format: Missing 'Action:' after 'Thought` in the logs when I set the model to `gap-3.5-tubo`.

This error does not exist when model is set to `gpt-4`.

The error does not seem to affect the results and the agent finishes the job.

I am using the following agent:

```
researcher = Agent(
  role='Researcher',
  goal='Discover new insights about Tesla Inc. and its stock',
  backstory="You're a world class reporter and researcher who is an expert in discovering news about Tesla Inc.",
  verbose=True,
  allow_delegation=False,
  tools=[SearchTools.search_news],
  llm=OpenAI(temperature=0.7, model_name="gpt-3.5-turbo")
  # llm=OpenAI(temperature=0.7, model_name="gpt-4")
)
```

**Comment by stoltzmaniac** [comment]
@rawmean - I had this issue during a previous release. Mine resolved after updating my crewai package

`pip install crewai --upgrade`

**Comment by joaomdmoura** [comment]
@rawmean I've update the README example to now work better, that said I'm working on a better fix to avoid tool hallucination
