### ISSUE TITLE
Spelling correction in README.md

### ISSUE THREAD

**Issue by aarongerber** [joaomdmoura/crewAI#163]
From [README.md](https://github.com/joaomdmoura/crewAI/blob/main/README.md)

Reads:
> I, [@joaomdmoura](https://github.com/joaomdmoura) (creator **or** crewAI),

Should read:
> I, [@joaomdmoura](https://github.com/joaomdmoura) (creator **of** crewAI),

**Comment by prabha-git** [comment]
Sent this pull request https://github.com/joaomdmoura/crewAI/pull/168

**Comment by joaomdmoura** [comment]
Thanks! Will merge that now 😎👉👉
