### ISSUE TITLE
Update wiki about local LLM to use updated langchain-community.llms

### ISSUE THREAD

**Issue by PiotrEsse** [joaomdmoura/crewAI#179]
Small update, just not to forget. As for incoming changes with langchain it would be nice to update doc and code to reflect changes. 
Change where - 

- Old code: from langchain.llms import Ollama
- New code: **from langchain_community.llms import Ollama**

error message:
```
LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import Ollama`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
```

**Comment by reaperkrew** [comment]
Hi @PiotrEsse I have created https://github.com/joaomdmoura/crewAI/pull/180 to address this issue
