### ISSUE TITLE
Import "crewai" could not be resolved

### ISSUE THREAD

**Issue by ifejam** [joaomdmoura/crewAI#186]
Import "crewai" could not be resolvedPylance

**Comment by greysonlalonde** [comment]
Need a full traceback @ifejam

**Comment by Haripritamreddy** [comment]
I have never used import crewai. Generally use 
`from crewai import Agent, Task, Crew, Process`

**Comment by greysonlalonde** [comment]
Closing, feel free to reopen @ifejam
