### ISSUE TITLE
example model file for ollama openhermes2.5-mistral

### ISSUE THREAD

**Issue by fxtoofaan** [joaomdmoura/crewAI#19]
would this be a correct modelfile to use for ollama openhermes2.5-mistral?

TEMPLATE """<|im_start|>system
{{ .System }}<|im_end|>
<|im_start|>user
{{ .Prompt }}<|im_end|>
<|im_start|>assistant
"""
PARAMETER num_ctx 4096
PARAMETER top_p 0.5
PARAMETER temperature 0
PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
PARAMETER stop "Observation"

**Comment by iplayfast** [comment]
You are on the wrong github, but here are some examples from my github page https://github.com/iplayfast/OllamaPlayground/tree/main/modelfiles 
The github page you want is https://github.com/jmorganca/ollama

**Comment by joaomdmoura** [comment]
hey @fxtoofaan that is the modelfile I used yes, but you can tune it in different ways if you want to 😉
