### ISSUE TITLE
Hierarchy HAAS Framework

### ISSUE THREAD

**Issue by iamthenickwalker** [joaomdmoura/crewAI#194]
David Shapiro's HAAS Framework (https://github.com/daveshap/OpenAI_Agent_Swarm) would fit perfectly with Crew AI. Is agent termination and creation possible by another set of AI agents on CrewAI?

**Comment by greysonlalonde** [comment]
I've got a skeleton project that integrates CrewAI @ [ArmAI](https://github.com/greysonlalonde/ArmAI) focusing on HAAS

**Comment by whoabuddy** [comment]
If you consider an agent to be just a valid `Agent()` object, then you could conceptually use the LLMs to create one when needed, provided you get the tools/abilities set correctly for the model you're running against.

My early thought on this was to have some external variables the LLM can set one-by-one with rolling context, e.g. role, backstory, tools, etc. The final output from each step could set the required field.

We have `hierarchical` mode now that assigns a manager to create/delegate tasks, and `autonomous` should be coming soon which I would guess will be a similar process of creating dynamic agents.

Same principals can apply to Tasks, Crews, and other objects too!
