### ISSUE TITLE
OpenAI GPT-3.5-turbo not supported?

### ISSUE THREAD

**Issue by williamgurzoni** [joaomdmoura/crewAI#197]
I'm trying to use GPT-3.5-turbo, but receiving this error message:

```
raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?', 'type': 'invalid_request_error', 'param': 'model', 'code': None}}
```

I'm importing `OpenAi` from `langchain_openai`.

It seems that v1 of OpenAI python package had some breacking changes, I'm wondering if it's related.
Thank you.

**Comment by joaomdmoura** [comment]
hey @williamgurzoni it should just work, can you share some of code around the issue?
Here is some examples on conneting with multiple LLMs: https://joaomdmoura.github.io/crewAI/how-to/LLM-Connections/

**Comment by rmgravina** [comment]
@williamgurzoni I dont know if this solution will be suited to you, but you can set the `llm` like this:

```python
llm = ChatOpenAI(openai_api_base=os.environ.get("OPENAI_API_BASE_URL"),
                 openai_api_key=os.environ.get("OPENAI_API_KEY"),
                 model_name=os.environ.get("MODEL_NAME")
                 )
```

and have in your `.env`file the following configs:

```cfg
OPENAI_API_KEY=<your-api-key>
OPENAI_API_BASE_URL="https://api.openai.com/v1"
MODEL_NAME ="gpt-3.5-turbo"
```

Dont foget to import the `dotenv` (`pip install python-dotenv`) package (and to invoke in the code using `load_dotenv()`)

```python
from langchain.chat_models.openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

#os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

llm = ChatOpenAI(openai_api_base=os.environ.get("OPENAI_API_BASE_URL"),
                 openai_api_key=os.environ.get("OPENAI_API_KEY"),
                 model_name=os.environ.get("MODEL_NAME")
```

This works for me, hope that helps!

p.s: The link that @joaomdmoura shared helpped me to get into this solution, thx

**Comment by williamgurzoni** [comment]
Perfect! That makes total sense @rmgravina. Thank you very much you both for adding so much info here!
I was able to get it working with your example.

I think I got stuck because of the [example](https://github.com/joaomdmoura/crewAI/blob/2010702880aa1d9b9c22f98ddeb9e01f1fb8a6e5/README.md?plain=1#L88) in the Readme:

```
  ...
  # llm=OpenAI(model_name="gpt-3.5", temperature=0.7)
  # For the OpenAI model you would need to import
  # from langchain_openai import OpenAI
  ...
```

I was trying to use `OpenAI` instead of `ChatOpenAI`.
As soon as I learn more about the project I'll be happy to contribute to a PR.

Great project guys, thanks.
