### ISSUE TITLE
Hierachial error

### ISSUE THREAD

**Issue by drewskidang** [joaomdmoura/crewAI#212]
<ipython-input-45-09d3ba9ba28e> in <cell line: 76>()
     78   tasks=[task1, task2],
     79   verbose=2,
---> 80   process=Process.hierarchical
     81 )
     82 

/usr/lib/python3.10/enum.py in __getattr__(cls, name)
    435             return cls._member_map_[name]
    436         except KeyError:
--> 437             raise AttributeError(name) from None
    438 
    439     def __getitem__(cls, name):

AttributeError: hierarchical

**Comment by joaomdmoura** [comment]
Weird, is this using main? because we didn't launch the new version yet with the `hierarchical` process

**Comment by drewskidang** [comment]
Oh sorry I thought you launched it bc I saw it in the docs. I tried pip install and installing from the source

**Comment by joaomdmoura** [comment]
M

**Comment by joaomdmoura** [comment]
My bad, I'll probably cut a new version between today and tomorrow :D
