### ISSUE TITLE
custom llm the openai env problem 

### ISSUE THREAD

**Issue by soragui** [joaomdmoura/crewAI#213]
when i using LMstudio , the doc have open_base_url env is :

OPENAI_API_BASE_URL

but the current one is:

OPENAI_API_BASE

**Comment by joaomdmoura** [comment]
Updating it ;)
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em sáb., 3 de fev. de 2024 às 18:25, soragui ***@***.***>
escreveu:
