### ISSUE TITLE
Pass a file to agents for use in their tools

### ISSUE THREAD

**Issue by williamzebrowskI** [joaomdmoura/crewAI#214]
My scenario is as follows:

I'm creating a chatbot (via gradio) and would like to see if when uploading a file on the interface, ie PDF, the file can be passed through the agents to use in one of their tools.  Ultimately, I want a pdf_analyzer agent to use its tool with the uploaded pdf provided by the user.  

Any ideas how to pass files or any documentation around this idea?

**Comment by r-joyce** [comment]
Take a look at the native tools provided by LangChain, which are natively supported: https://python.langchain.com/docs/integrations/tools/filesystem

If none of those tools work for what you're trying to do you can always build your own custom tools for your agents
https://python.langchain.com/docs/modules/agents/tools/custom_tools
