### ISSUE TITLE
ModuleNotFoundError: No module named 'crewai'

### ISSUE THREAD

**Issue by Mehownew** [joaomdmoura/crewAI#224]
Getting this error when running example crewai:

line 4, in <module>
    from crewai import Agent, Task, Crew, Process
ModuleNotFoundError: No module named 'crewai'

python 3.10.5
Crewai 0.5.0

**Comment by joaomdmoura** [comment]
hey @Mehownew did you install it? with `pip install crewai==0.5.0`
I can double check doing a pip freeze and checking with crewai is in the list

**Comment by Mehownew** [comment]
hey @joaomdmoura  thanks for a quick response! 
I've uninstalled crewai, openai and lanchain modules and reinstalled via PowerShell (VS code terminal did not work previously) and its working now. 
Note: naming the test file crewai.py might have broken it..

**Comment by joaomdmoura** [comment]
Nice! great to hear it worked out!

**Comment by joejoj0** [comment]
having the same problem as well. using VS code. environment and python 3.11.
