### ISSUE TITLE
Name is already taken by a company

### ISSUE THREAD

**Issue by SuperMalinge** [joaomdmoura/crewAI#28]
the name may cause some issues since there is already a company like: https://www.crew-ai.com/

**Comment by joaomdmoura** [comment]
I got crewai.io, so maybe I need to host something there 🤔

**Comment by SuperMalinge** [comment]
Its just my 2 cents, but you could get in trouble in the future if the company is going for copyright infringement

**Comment by joaomdmoura** [comment]
Indeed, good call, I'll consult someone on it and maybe ping the developer behind it just in case
