### ISSUE TITLE
Connection to telemetry.crewai.com timed out.

### ISSUE THREAD

**Issue by Adamchanadam** [joaomdmoura/crewAI#292]
When I executed  script on Crew AI  it returned the error "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='telemetry.crewai.com', port=4318): Max retries exceeded with url: /v1/traces (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029E70AFB590>, 'Connection to telemetry.crewai.com timed out. (connect timeout=15)'))', which blocked the task at the end.

I tried to bypass this issue by adding share_crew=False in Crew(), but the error persisted. Is there any solution for this issue? may be my port was being blocked by firewall ? 
I don't mind to share the data via telemetry indeed but first of all need the agents work properlly . 

Thanks,

Adam

**Comment by chrissonntag** [comment]
Duplicate. See #254

**Comment by Adamchanadam** [comment]
> Duplicate. See #254

thanks . 
Is there any solution yet ?

**Comment by chrissonntag** [comment]
Nope, unfortunately not. But you may comment on the other issue for more weight an be so kind to close this issue. Hopefully we're getting there anytime soon.
