### ISSUE TITLE
How to use CrewAI with Openrouter's free LLMs?

### ISSUE THREAD

**Issue by vanetreg** [joaomdmoura/crewAI#296]
There are a bunch of good LLMs there for free or with huge discount:
https://openrouter.ai/models?q=free&o=top-weekly
so it is definitely a real option for many of us.

I tried it using LlamaIndex's OpenRouter class:
https://docs.llamaindex.ai/en/stable/examples/llm/openrouter.html#openrouter
but it caused errors...

I think **adding info to CrewAI docs how to use Hugging Face and OpenRouter LLM inference with CrewAI** would be beneficial for many of us not wanting to use OpenAI or local LLMs.

**Comment by vanetreg** [comment]
Langchain's ChatOpenAI class should be used, as this video explains in its last part:
https://www.youtube.com/watch?v=opR3LozV3NM&list=WL&index=1

**Comment by sjssmits** [comment]
import os
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
llm = ChatOpenAI (model="google/gemma-7b"),
api_key="API_KEY"
base_url="https://openrouter.ai/api/v1'')

**Comment by ShirinPullot** [comment]
Did this work?

**Comment by srishrachamalla7** [comment]
yes its working
