### ISSUE TITLE
 OPENAI_API_BASE set to local llm but WebsiteSearchTool still requires OpenAI api key

### ISSUE THREAD

**Issue by oswaldo-grassiotto** [joaomdmoura/crewAI#303]
Attempting to run crewAI with a locally hosted mistral-7b model (LM studio) following these instructions:
https://docs.crewai.com/how-to/LLM-Connections/#openai-compatible-api-endpoints

WebsiteSearchTool returns the following error:

Inserting batches in chromadb:   0%|          | 0/1 [00:00<?, ?it/s]
Failed to add batch due to a bad request: Error code: 401 - {'error': {'message': 'Incorrect API key provided: NA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Successfully saved https://news.mit.edu (DataType.WEB_PAGE). New chunks count: 0

So all it ends up retrieving from the website is the title. Tested with gpt-4 too and everything works.

**Comment by WorldICTown** [comment]
I thoroughly enjoyed reading this.Learned a lot. The writing style is PROFESSIONAL, and the content is both interesting and valuable. Looking forward to more! By the way,if you have any ICs' need, find all your chip needs at https://www.worldictown.com/ – your one-stop destination for a diverse range of chips and solutions.You can contact us on Worldictown

**Comment by Malthehave** [comment]
Hi. Did you find a solution for this?

**Comment by joaomdmoura** [comment]
Yes, we now updates the tool on the latest version to support opensource embeddings.
These RAG tools before would only work with GPT-4 to generate embeddings, that is not the case anymore, here is an example on how you cna use other models: https://docs.crewai.com/tools/WebsiteSearchTool/#customization-options
lmk if it doesn't work 🙏🏼

**Comment by Malthehave** [comment]
Thanks for the quick reply @joaomdmoura! I was running into the same error (`Incorrect API key provided`) without using any tools. Turned out it was because I had memory=True in the Crew object. I guess the memory also uses OpenAI for embeddings?

**Comment by joaomdmoura** [comment]
Yes, but you can also config it the same way with and `Embedder` option
> (optional)	Configuration for the embedder to be used by the crew. mostly used by memory for now

**Comment by Malthehave** [comment]
Oh cool! Thanks

**Comment by joaomdmoura** [comment]
we now have specific docs for that too: docs.crewai.com/core-concepts/memory

**Comment by vladeziegler** [comment]
I'm trying to use WebsiteSearchTool for a specific URL and Llama 2 but it keeps on saying that my tool is not defined. 

It works when I configure Llama with a generic WebsiteSearchTool, or when I use "website" as a parameter. But it doesn't work when I try to combine both. Any idea why? Here is how I set it up:

`    company_tool = WebsiteSearchTool(
        config=dict(
           website='https://www.amplemarket.com/',
            llm=dict(
                provider="huggingface",
                config=dict(
                    model=model_name,
                    tokenizer=tokenizer
                ),
            ),
            embedder=dict(
                provider="huggingface",
                config=dict(
                    model=model_name,
                    tokenizer=tokenizer
                ),
            ),
        )
    )`

**Comment by wahidur028** [comment]
> Yes, we now updates the tool on the latest version to support opensource embeddings. These RAG tools before would only work with GPT-4 to generate embeddings, that is not the case anymore, here is an example on how you cna use other models: https://docs.crewai.com/tools/WebsiteSearchTool/#customization-options lmk if it doesn't work 🙏🏼

@joaomdmoura, is it possible to share any notebook example from end to end?

**Comment by m-hamza-hashim** [comment]
@joaomdmoura  the url referred doesn't provide any help... still can't use websearchtool with any other llm
