### ISSUE TITLE
No valid dependencies for openai, langchain with crewai

### ISSUE THREAD

**Issue by aiswaryasankar** [joaomdmoura/crewAI#306]
I've tried nearly every permutation of dependencies but keep running into these conflicts 
Also why is crewai dependent on such an old version of openAI?  Even if I downgrade to openai 0.28.1 it throws errors
since the other apis have moved on. e.g. 

```    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai'```

Dep issues - 
```
crewai 0.1.7 requires langchain<0.0.352,>=0.0.351, but you have langchain 0.1.10 which is incompatible.
crewai 0.1.7 requires openai<0.29.0,>=0.28.1, but you have openai 1.13.3 which is incompatible.
```

**Comment by joaomdmoura** [comment]
Oh you should be updating crewAI to its latest version 0.19.0 :) way better
and more features
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em dom., 3 de mar. de 2024 às 20:54, aiswaryasankar <
***@***.***> escreveu:

**Comment by Wladastic** [comment]
This is fixed by updating crewai as well as langchain dependency.

**Comment by joaomdmoura** [comment]
thanks!
