### ISSUE TITLE
Forceful Use Of Tools

### ISSUE THREAD

**Issue by ROHUE** [joaomdmoura/crewAI#327]
I am using Gemini and I seem to have troubles with running an agent that doesn't resort to using a tool to perform a task.

I want the agent to do the task itself without depending on a tool and I am wondering if this is possible, or does CrewAI force agents to use tools.

**Comment by aliensouls** [comment]
hey did you figure out in which case agents will resort to using provided tools and in which case they just complete task without it? I am still confused by what logic they use, since nothing in docs about it...
