### ISSUE TITLE
WARNING: crewai 0.1.7 does not provide the extra 'tools'

### ISSUE THREAD

**Issue by custom-build-robots** [joaomdmoura/crewAI#347]
Hello all,
today I tried to install crewAI in a fresh virtual environment. Starting with `pip install crewai` followed by the command `pip install 'crewai[tools]'` and I got the following error.

```
Requirement already satisfied: crewai[tools] in ./venv_2/lib/python3.8/site-packages (0.1.7)
WARNING: crewai 0.1.7 does not provide the extra 'tools'
```
I am really wondering why not the latest version 0.2.x is installed but 0.1.7 the old one.

Any idea whats wrong here maybe with the instructions or what I am trying?

Thanks

**Comment by custom-build-robots** [comment]
The solution was to upgrade from python 3.8.x to 3.11.x and now I am able to use the latest version of creaAI.

**Comment by assad-ua** [comment]
I am using Python 3.11.8, but on running crewai[tools] i get this error:
ERROR: Invalid requirement: "'crewai[tools]'"

**Comment by Mampha** [comment]
@assad-ua use pip install crewai[tools] instead without quotation mark. Let's see the output.

**Comment by assad-ua** [comment]
It worked. Thanks

**Comment by Bitsy-Chuck** [comment]
Using python 3.12.4 and getting 
`WARNING: crewai 0.5.0 does not provide the extra 'tools'` 

with ` pip3 install'crewai[tools]' `

**Comment by Bitsy-Chuck** [comment]
worked with python 3.11.9

**Comment by naveenfaclon** [comment]
`ModuleNotFoundError: No module named 'crewai_tools'`

**Comment by RuohanZhong21** [comment]
Using python 3.11.9 but also getting 
WARNING: crewai 0.5.0 does not provide the extra 'tools' 
with pip install 'crewai[tools]'

Why???

**Comment by EricHidekiMiyahara** [comment]
Same here...
