### ISSUE TITLE
ImportError: cannot import name 'Agent' from partially initialized module 'crewai' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Verfinix** [joaomdmoura/crewAI#35]
I am new here, wanted to try the sample. But having error

ImportError: cannot import name 'Agent' from partially initialized module 'crewai' (most likely due to a circular import)

Any suggestion to fix this ?

I am using conda, python=3.10, have also try python=3.11, both not working

**Comment by juangonbeamsuntory** [comment]
I had the same use case, just change your python file name where you are executing the code to anything different from "crewai*"

**Comment by Verfinix** [comment]
Thanks. This solved my issue.

**Comment by joaomdmoura** [comment]
❤️  thanks folks

**Comment by prabhatkgupta** [comment]
This works. Thanks @juangonbeamsuntory
