### ISSUE TITLE
Read The Docs 

### ISSUE THREAD

**Issue by greysonlalonde** [joaomdmoura/crewAI#36]
@joaomdmoura mind if I get started on sphinx / readthedocs ? I think many users would benefit from this.

**Comment by joaomdmoura** [comment]
Nah, sounds like a great plan and the more docs the better, people would def benefit from it, feel free to go!

**Comment by joaomdmoura** [comment]
Someone suggested me https://squidfunk.github.io/mkdocs-material/

It has google analytics setup and will help better track interest to inform back the project, I haven't used it yet tho, but feels like a better option for that, any takes?

**Comment by joaomdmoura** [comment]
Yup, let's do https://squidfunk.github.io/mkdocs-material/ I think metrics will be helpful to inform on content needed and roadmap

**Comment by joaomdmoura** [comment]
New docs initial kick off starter now starting to write it
