### ISSUE TITLE
Crew.Kickoff is asking for self 

### ISSUE THREAD

**Issue by MrAech** [joaomdmoura/crewAI#378]
result = Crew.kickoff()
             ^^^^^^^^^^^^^^
TypeError: Crew.kickoff() missing 1 required positional argument: 'self'

python == 3.11.4

using ollama model == llama2

**Comment by joaomdmoura** [comment]
I think you are calling it wrong you are calling kickoff as if it was a
class method, on the Crew, while you want to do it on the instance of a
crew :)


Em seg., 25 de mar. de 2024 às 03:58, MrAech ***@***.***>
escreveu:
