### ISSUE TITLE
Repetition for Self Improvement

### ISSUE THREAD

**Issue by Vasanthengineer4949** [joaomdmoura/crewAI#421]
I am unable to see how I can self improve agents. Can you please let me know if support is there for this already how I can do this and if not a support for this like in the AutoGen Studio

**Comment by xitex** [comment]
Use autogen, author doesn't look here and is probably busy with the commercial version.

**Comment by joaomdmoura** [comment]
Hey there @Vasanthengineer4949 yes crewAI uses repetition for auto improvement if you enable memory, you do so on the crew level by setting the attribute `memory=True` you can see the attribute explained here: https://docs.crewai.com/core-concepts/Crews/#memory-utilization
