### ISSUE TITLE
set_agent_executor overwrites custom callbacks in agent.py

### ISSUE THREAD

**Issue by max-m-roy** [joaomdmoura/crewAI#424]
```  def set_agent_executor(self) -> "Agent":
        """set agent executor is set."""
        if hasattr(self.llm, "model_name"):
            self.llm.callbacks = [
                TokenCalcHandler(self.llm.model_name, self._token_process)
            ]
        if not self.agent_executor:
            if not self.cache_handler:
                self.cache_handler = CacheHandler()
            self.set_cache_handler(self.cache_handler)
        return self
```
        
line 152 -> if hasatter(self.llm, "model_name"):
line 153 -> self.llm.callbacks = [...] (this overwrites all other call-backs that have been added when initialising instead of just appending the call-backs. This needs to update. not overwrite.

**Comment by joaomdmoura** [comment]
Nice, good  catch will fix it now :)

**Comment by joaomdmoura** [comment]
Fixed, new minor version is out 0.27.1 :) might take a few mionutes to propagate

**Comment by max-m-roy** [comment]
Legend. And what a quick response.

**Comment by TomTom101** [comment]
This is imo still the case:
```python
    litellm.callbacks = callbacks

    def call(self, messages: List[Dict[str, str]], callbacks: List[Any] = []) -> str:
        with suppress_warnings():
            if callbacks and len(callbacks) > 0:
                litellm.callbacks = callbacks

```
[see](https://github.com/crewAIInc/crewAI/blob/093259389e2a3afaa45365ec275fc941c68dc028/src/crewai/llm.py#L123)

Any callbacks passed to a `LLM` like so
```python
llm = LLM(model="gpt-4o", temperature=0.4, callbacks=["langsmith"])
```
will be overwritten by the `TokenCalcHandler` callback

**Comment by TomTom101** [comment]
Even when hardcoding it to "langsmith" I cannot get litellm to log my requests, other than the one using native Langchain tools. The completion calls are nowhere visible. Visible in Langtrace, but I prefer Langsmith A LOT over Langtrace. Bummer.
