### ISSUE TITLE
Access to internal files?

### ISSUE THREAD

**Issue by ViperVille007** [joaomdmoura/crewAI#43]
I've been exploring this repo as a possible alternative to Autogen, which you rightfully mentioned in your comparison as well. 
One of their features I really liked was that we are able to give the agents access to our own files by putting them in the working directory and then the agents are able to modify their content, extract information from them, etc. 
I was wondering if CrewAI already has a similar option available or you are planning to add something like that in future?!

**Comment by joaomdmoura** [comment]
You can actually do that right now using LangChain Tools: https://python.langchain.com/docs/integrations/tools/filesystem
But I think we might benefit from having an internal implementation of that as well as I had some issues with reading files using that tool in the past

**Comment by TerminalGravity** [comment]
@joaomdmoura any possibility in the future of using the OpenAI/assistants/retrieval tool as an internal implementation

**Comment by joaomdmoura** [comment]
Yes, I would love to offer support for OpenAI assistants, and we are in the process or building default crewAI tools you will be bale to sue that will include RAG and Filesystem, I'm closing this for now, but there will come as part of a new packagua called crewai-tools
