### ISSUE TITLE
Unable to pass extra values to the task so I can access them in the task callback function.

### ISSUE THREAD

**Issue by absolutemadla8** [joaomdmoura/crewAI#435]
I want to pass a document_id to the task so that it can be accessed by my callback function for api calls to populate a specific document with the result on another application.

when I try to access it by output.doc_id, it says 'TaskOutput' object has no attribute 'doc_id'.

How can I make this work?

**Comment by nkeilar** [comment]
@absolutemadla8 How did you solve the issue?

**Comment by absolutemadla8** [comment]
Pass in the value to the Task itself in the Crew Task's 

`class SearchCrew:
    def __init__(self, query, search_id):
        self.query = query
        self.search_id = search_id

    def run(self):
        agents = MemoAssistAgents()
        tasks = SearchAssistTask(search_id=self.search_id)`
        
  an then in the tasks
  
  `class SearchAssistTask():
    def __init__(self, search_id):
        self.search_id = search_id

    def callback_function(self, output):
        url = "http://127.0.0.1:8000/webhook/createSearch"
        data = {
            "result": output.raw_output,
            "search_id": self.search_id
        }
        try:
            response = requests.post(url, json=data)
            response.raise_for_status()  # Raise an exception for unsuccessful status codes
            print(f"""
            Task completed!
            output: {output.raw_output}
            Output sent to API endpoint.
            Response: {response.json()}
            """)
        except requests.exceptions.RequestException as e:
            print(f"""
            Task completed!
            output: {output.raw_output}
            Error sending output to API endpoint: {str(e)}
            """)`
