### ISSUE TITLE
ImportError when importing Agent, Task, Crew from CrewAI

### ISSUE THREAD

**Issue by vsaroopchand** [joaomdmoura/crewAI#454]
When attempting to import Agent, Task, and Crew from the crewai package, an ImportError is thrown. The error occurs in the crewai package, specifically when importing RunnableAgent from langchain.agents.agent.

**Environment:**

Python version: 3.11.1
CrewAI version: 0.28.7
Langchain version: 0.1.15
Steps to Reproduce:

Install the above versions of Python, CrewAI.

Run the following import statement in a Python script:
`from crewai import Agent, Task, Crew`

**Expected Result:** The modules Agent, Task, and Crew are imported without any errors.

**Actual Result:** An ImportError is thrown, indicating an issue with importing RunnableAgent from langchain.agents.agent.

**Error Log:**
---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
----> 1 from crewai import Agent, Task, Crew

----> 1 from crewai.agent import Agent
      2 from crewai.crew import Crew
      3 from crewai.process import Process

----> 5 from langchain.agents.agent import RunnableAgent
      6 from langchain.agents.tools import tool as LangChainTool
      7 from langchain.tools.render import render_text_description
```

**Comment by joaomdmoura** [comment]
can you share mote about the environment? Is this a virtuasl env of sort?

**Comment by vsaroopchand** [comment]
Correct, this is a virtual environment. The only dependencies that are installed are crew, and crew-tools

**Comment by vsaroopchand** [comment]
Project moved to a dev container, thanks.

**Comment by Apuprg** [comment]
Hello, I am facing same issue. Anyone got the solution?

**Comment by qiudanWang** [comment]
I can not import Dispatcher! Is it in a special version?

from crewai import Dispatcher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Dispatcher' from 'crewai' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/crewai/__init__.py)

**Comment by sheunaluko** [comment]
I am also having this issue, looking for a solution

**Comment by amansingh9097** [comment]
I'm facing this issue as well.

  File "E:\Project\v3\src\agents.py", line 2, in <module>                                                                      from crewai import Agent 
ImportError: cannot import name 'Agent' from 'crewai' (unknown location)

**Comment by s1l1m** [comment]
only change your filename. your file name should not be crewai.py

**Comment by mohitarpan** [comment]
I am also facing the same error and I am using virtual environment 

(top) PS D:\3d_mode> python main.py
Traceback (most recent call last):
 File "D:\3d_mode\main.py", line 1, in <module>
  from crew import ModelGenerationCrew
  File "D:\3d_mode\crew.py", line 5, in <module>
    from agents import (
ImportError: cannot import name 'create_design_agent' from 'agents' (unknown location)

please me as possible

**Comment by GopiChand-N** [comment]
im also facing the same error while importing like this
from crewai import Agent, Task, Crew

the error im getting is : UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1980: character maps to <undefined>

**Comment by pramodklal** [comment]
Is any solution of this issue?

**Comment by Pearls-administrative** [comment]
use python 3.11.9

**Comment by fehmisener** [comment]
Make sure your file name is not `crewai.py`
