### ISSUE TITLE
Error with pydantic dependencies

### ISSUE THREAD

**Issue by pavanjava** [joaomdmoura/crewAI#516]
When we install crewai with bellow instruction.
`pip install crewai`
Now try to follow the how to guide to run the example. below is the error message.

`ImportError: cannot import name 'Undefined' from 'pydantic.fields'`
Note: pydantic-2.7.1 pydantic-core-2.18.2 as dependencies

if we downgrade the pydantic to `pydantic-1.10.11`, below is the error message.
`ImportError: cannot import name 'InstanceOf' from 'pydantic'`

i think crewai is completely screwed up with dependency issues. please let me know if you have a plan of releasing a stable version of the library ?

System Details: 

1. processor: M1 Pro
2. OS: Sonoma 14.4.1

**Comment by theCyberTech** [comment]
What else have you installed in your virtual environment?, I'm assuming you are running in a virtual environment such as venv or Conda?
