### ISSUE TITLE
 circular import

### ISSUE THREAD

**Issue by Ai-ENGINEER-s** [joaomdmoura/crewAI#537]
Hi , 
I am recently encountered a problem when trying to run crew . It's always telling me that 
I am on circular import from the package crewai

**Comment by FaulTTY** [comment]
Is the Python file you're trying to run called `crewai.py`? That would be the culprit. You'd need to rename it to something else, e.g. `main.py`.

https://github.com/joaomdmoura/crewAI/issues/35

**Comment by joaomdmoura** [comment]
Yup, I pretty sure that will be the case
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em ter., 30 de abr. de 2024 às 17:03, faulTTY ***@***.***>
escreveu:

**Comment by Ai-ENGINEER-s** [comment]
Exactly , this was the error , i was naming the file crewai.py and when i try to import packages i got this error . 
Thank you for your support
