### ISSUE TITLE
How to increase agent max iteration limit

### ISSUE THREAD

**Issue by matsuobasho** [joaomdmoura/crewAI#56]
Posted this originally on the examples repo but more visibility here and others may run into same issue.

I run the web search example using an open-source model via a LMStudio server and get the following output at the end:
```
> Finished chain.
Task output: Agent stopped due to iteration limit or time limit.
######################
Agent stopped due to iteration limit or time limit.
```

I've seen the Langchain [issue](https://github.com/langchain-ai/langchain/issues/6025), but having difficulty figuring out where I pass this `max_iterations` argument in the CrewAI codebase.  

Here's the code for reference:

```python
import os
from crewai import Agent, Task, Crew, Process
from langchain.chat_models import ChatOpenAI as OpenAI
from langchain.tools import DuckDuckGoSearchRun

local_openai_client = OpenAI(
    base_url="http://localhost:1234/v1", api_key="not-needed", temperature=0.4
)

search_tool = DuckDuckGoSearchRun()

# Define your agents with roles and goals
researcher = Agent(
  role='Senior Research Analyst',
  goal='Uncover cutting-edge developments in AI and data science in',
  backstory="""You are a Senior Research Analyst at a leading tech think tank.
  Your expertise lies in identifying emerging trends and technologies in AI and
  data science. You have a knack for dissecting complex data and presenting
  actionable insights.""",
  verbose=True,
  allow_delegation=False,
  tools=[search_tool],
  llm=local_openai_client
)
writer = Agent(
  role='Tech Content Strategist',
  goal='Craft compelling content on tech advancements',
  backstory="""You are a renowned Tech Content Strategist, known for your insightful
  and engaging articles on technology and innovation. With a deep understanding of
  the tech industry, you transform complex concepts into compelling narratives.""",
  verbose=True,
  llm=local_openai_client,
  allow_delegation=True
)

# Create tasks for your agents
task1 = Task(
  description="""Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.
  Compile your findings in a detailed report.""",
  agent=researcher
)

task2 = Task(
  description="""Using the insights from the researcher's report, develop an engaging blog
  post that highlights the most significant AI advancements.
  Your post should be informative yet accessible, catering to a tech-savvy audience.
  Aim for a narrative that captures the essence of these breakthroughs and their
  implications for the future.""",
  agent=writer
)

# Instantiate your crew with a sequential process
crew = Crew(
  agents=[researcher, writer],
  tasks=[task1, task2],
  verbose=2, # Crew verbose more will let you know what tasks are being worked on, you can set it to 1 or 2 to different logging levels
  process=Process.sequential # Sequential process will have tasks executed one after the other and the outcome of the previous one is passed as extra content into this next.
)

# Get your crew to work!
result = crew.kickoff()

print("######################")
print(result)
```

**Comment by joaomdmoura** [comment]
Not yet, but I'm have an issues to implement this with another fix as well: https://github.com/joaomdmoura/crewAI/issues/65

**Comment by tjthejuggler** [comment]
This is marked as completed, but I still don't see any way to deal with it anywhere. Where do we put the setting to increase the time and iterations? nearly everything i try just comes back with this message 'Agent stopped due to iteration limit or time limit.'

**Comment by matsuobasho** [comment]
I think it was closed here in order to deal with it in #65 .  
I'm on the same page as @tjthejuggler , cannot proceed experimenting with CrewAI because this doesn't work.  I don't want to keep feeding the OpenAI beast.  
@joaomdmoura , if you can give some pointers, I'd be glad to investigate this on my own and try to contribute to the development.  Thanks

**Comment by joaomdmoura** [comment]
Exactly, the code is actually ready I'll push it today and it will be part of the next version that I'll cut later this week

**Comment by MR-GREEN1337** [comment]
Issue :
Function continues execution after displaying "finished chain"

Description:
When executing the function kickoff_crew, it sometimes displays "finished chain" indicating the completion of the crew's work. However, even after displaying this message and the wanted ouput, the function continues to execute further, which is unexpected behavior.

**Comment by anmol-aidora** [comment]
There are a lot of parameters for which I am having difficulty understanding how I can change them, one of them being max_iter, but also things like how do I access and change the AgentExecutor, ToolUsage, etc classes. Has anyone been able to figure it out yet?
