### ISSUE TITLE
Issue importing CrewAI

### ISSUE THREAD

**Issue by sarat9** [joaomdmoura/crewAI#566]
index.py just includes one line.

```
from crewai import Agent, Task, Process, Crew

```

I am facing the below error.

```
/Library/Python/3.11/lib/python/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(

```

**Comment by alexfazio** [comment]
Hi @sarat9 

Please provide the complete error output. If the script is not executing, the issue lies elsewhere.

This is not an error but a deprecation warning, which should not impact the overall execution.

**Comment by sarat9** [comment]
Hi @alexfazio, 
Thanks.. was able to fix..
Just realized expected_output parameter is mandatory now.
Thank you and closing the issue.
