### ISSUE TITLE
research example doesn't generate a final blog post.

### ISSUE THREAD

**Issue by naseerfaheem** [joaomdmoura/crewAI#57]
I have been trying the example on the landing page using Ollama and TextGen-Webui's OpenAI API wrapper. I followed all the steps, but the writer doesn't write the summary at the end. The conversation ends with the steps and advice on how to write the blog post, not the actual blog post. Is there a way we can control the conversation by telling the agents that the task is not done yet? I  saw in Matt Berman's video that the conversation ended with a summary of the blog post, but it doesn't work for some reason when I try it. 
![image](https://github.com/joaomdmoura/crewAI/assets/38170316/91cd43ae-24c4-42e7-8ade-c5e2a46d112d)

And when I read LangChain's output, I see the following errors: 
Invalid Format: Missing 'Action:' after 'Thought:
![image](https://github.com/joaomdmoura/crewAI/assets/38170316/2f50ec46-917a-450e-81fe-ec6fb1063abb)

**Comment by joaomdmoura** [comment]
Hey @naseerfaheem good point, I believe the tasks could have been wrote better to produce the final expected resulted.
I've now updated the readme with better tasks descriptions, and it should work.
