### ISSUE TITLE
Request: Ability to limit the amount of LLM API calls per minute

### ISSUE THREAD

**Issue by mindwellsolutions** [joaomdmoura/crewAI#58]
When using CrewAI with the Free Gemini Pro API that has a limit of 60 API calls per minute. It would be incredibly helpful to have a simple way to define the max LLM API calls that can take place per minute, so people can use free LLM API's without going over the max threshold which blocks access for an hour or more.

Much thanks in advance!

**Comment by haseeb-heaven** [comment]
Yes Please add Google gemini Model support
