### ISSUE TITLE
running ollama in wsl ubuntu, running fine, but with crewai name 'ollama' is not defined

### ISSUE THREAD

**Issue by tendaysaweek** [joaomdmoura/crewAI#59]
please see the screenshot below.
running ollama directly - not problem, but  running crewais.py yields: name 'ollama' is not defined
![ollama](https://github.com/joaomdmoura/crewAI/assets/69711075/d890d4ef-10c7-4d9e-ad0f-9838cc5150b9)

**Comment by joaomdmoura** [comment]
@tendaysaweek I believe this is a problem in your code, you should import Ollama and load a model you have downloaded:

```python
from langchain.llms import Ollama = Ollama(model="openhermes")
```

Then you can pass it to the agent initialization

```python
Agent(
  #...
  llm=ollama_llm
)
```

The README has an example on this now.

**Comment by tendaysaweek** [comment]
Hi Joao,
thank you for the swift reply. 
i did use the code from the readme initially and also try changing to mistral. 
didn't succeed. 
please see below
![Capturec](https://github.com/joaomdmoura/crewAI/assets/69711075/5701d94c-2e54-460b-8c2a-d11928dddb16)
![Capturea](https://github.com/joaomdmoura/crewAI/assets/69711075/42be06d1-3078-489d-b574-a030373f175d)
![Captureb](https://github.com/joaomdmoura/crewAI/assets/69711075/caeffb2b-2fc9-4fdb-a95d-327d8af0362d)
