### ISSUE TITLE
Add tool groups

### ISSUE THREAD

**Issue by iplayfast** [joaomdmoura/crewAI#62]
A problem I've been having with local llm, is that not all tools work, or I don't know tools that are available. 
As an enhancement, Add toolgroups. I'm suggesting that instead of looking up the needed tools, we have predefined functions for common tools. 

I envision something like:
```
from crewai import Agent, Task, Crew, Process, Toolgroups

researchtools = Toolgroups("webtools", "calctools") # webtools is browser stuff, calctools is eval stuff. 
financetools = Toolgroups("finance", "financemath") #yhfinance common math tools used in finance

researcher = agent {....
      tools = reasearchtools
...
```

**Comment by joaomdmoura** [comment]
Yup, we are building this through a separate package, I think it will be killer and make it super easy to use, hopping to get it out before the next version of crew
