### ISSUE TITLE
Unauthorized Error (403) when Using SERPER_API_KEY for Google Search

### ISSUE THREAD

**Issue by 0x11c11e** [joaomdmoura/crewAI#633]
**Description:**

Whenever the software attempts to search in Google using the SERPER_API_KEY, I encounter an unauthorized error despite the API key being set correctly.

**Steps to Reproduce:**

1. Run the software with the correctly set SERPER_API_KEY.
2. Trigger a Google search action, such as

```plaintext
Action: Search the internet
Action Input: {"search_query": "Predictions for used car market in 2024"}
```

**Expected Result:**

The software should perform the Google search and return the relevant results.

**Actual Result:**

The following error message is returned:

`{'message': 'Unauthorized.', 'statusCode': 403}`

**Additional Context:**

Log Output:

```plaintext
> Entering new CrewAgentExecutor chain...
To accomplish this task, the first thing I need to do is to gather data about the current trends in the used car market, factors that influence the prices, and any predictions available for 2024. This will allow me to make an educated guess about whether the prices of used cars will go up or down in 2024.

Action: Search the internet
Action Input: {"search_query": "Predictions for used car market in 2024"} 

{'message': 'Unauthorized.', 'statusCode': 403}
```

**Environment:**

Software Version: 
- crewai 0.28.8
- crewai-tools 0.1.6
- Python 3.12.3
- pip 24.0

Operating System: Windows
Additional Details: Jupyter

**Comment by gadgethome** [comment]
Please can you try with the latest version. I just tested it and worked ok

crewai                                   0.30.11
crewai-tools                             0.2.6

**Comment by 0x11c11e** [comment]
I got the exact same issue with the latest versions. 

`
pip install crewai==0.30.11 crewai_tools==0.2.6 langchain_community
`

**Comment by theCyberTech** [comment]
What website is it trying to access

**Comment by wildcolor** [comment]
Are you using the local LLMs? I haven't got any success with any of the local LLMs with search tools...

**Comment by 0x11c11e** [comment]
> What website is it trying to access

It is trying to use scaleserp.com to perform a search on google. 



> Are you using the local LLMs? I haven't got any success with any of the local LLMs with search tools...

No. It is openai api. 

I have tested on both windows and Linux, in jupyter and out of it, but the same issue.

**Comment by michaelc2005** [comment]
Newbie here, but I had a similar issue. It was very, very frustrating... I had gotten an API key from scaleserp.com, but I finally figured out what was actually required was an API key from serper.dev. Now all of those SerperDevTool searches are working for me.

**Comment by ashitpatel** [comment]
Thanks @michaelc2005 for providing an answer. I ran into the same issue (got a key from scaleserp.com instead of serper.dev). Following your instructions fixed it.

**Comment by ashitpatel** [comment]
Thanks @michaelc2005 for providing an answer. I ran into the same issue (got a key from scaleserp.com instead of serper.dev). Following your instructions fixed it.

**Comment by mintymac** [comment]
@michaelc2005 I did exactly the same thing and was driving myself nuts.  Thank you!

**Comment by Ruffy45** [comment]
> Newbie here, but I had a similar issue. It was very, very frustrating... I had gotten an API key from scaleserp.com, but I finally figured out what was actually required was an API key from serper.dev. Now all of those SerperDevTool searches are working for me.

THANK YOU SO MUCH , i was losing my mind over it

**Comment by fenil210** [comment]
what's the final solution for the issue mentioned by @0x11c11e 
I  am facing the same "'message': 'Unauthorized.', 'statusCode': 403}" from serverdev API.

tried many combinations of langchain, langchain-core, crewAI version, not working.

please state your working versions if running

**Comment by 0x11c11e** [comment]
> what's the final solution for the issue mentioned by @0x11c11e I am facing the same "'message': 'Unauthorized.', 'statusCode': 403}" from serverdev API.
> 
> tried many combinations of langchain, langchain-core, crewAI version, not working.
> 
> please state your working versions if running

What @michaelc2005 wrote is the final solution.

**Comment by fenil210** [comment]
I’ve already taken API from server dev only, it was working till 10 PM,
after 10 PM it stopped working even i am left with 2000 credits

**Comment by mariosantos2025** [comment]
> serper.dev.

saved me from suicide thanks!

**Comment by xsuryanshx** [comment]
> Newbie here, but I had a similar issue. It was very, very frustrating... I had gotten an API key from scaleserp.com, but I finally figured out what was actually required was an API key from serper.dev. Now all of those SerperDevTool searches are working for me.

Thankyou man, saviour!

**Comment by viniciusgribas** [comment]
> Newbie here, but I had a similar issue. It was very, very frustrating... I had gotten an API key from scaleserp.com, but I finally figured out what was actually required was an API key from serper.dev. Now all of those SerperDevTool searches are working for me.

Thanks a lot! 🥇

**Comment by ktnabeel** [comment]
I created the account here https://serpapi.com/ai-overview instead of https://serper.dev/ this was the problem now its working for me
