### ISSUE TITLE
Unable to use crewAI with instructor version ^1.2.6

### ISSUE THREAD

**Issue by syberkitten** [joaomdmoura/crewAI#689]
Hi
What would it take to upgrade the Instructor library underneath to the latest version?
seems like current instructor is **^0.5.2.**

The current version of instructor that I'm using is  (**^1.2.6**).

Since i need crew in the same project I cannot install it.

**Comment by joaomdmoura** [comment]
Let me double check but I think we can update it

**Comment by syberkitten** [comment]
Please use the latest version of instructor if you can :)
thanks a lot.

**Comment by ezodude** [comment]
Hi, I'm having a similar issue.

Cannot install CrewAI in a project that uses `typer ^0.12.3` because `instructor ^0.5.2` depends on `typer (>=0.9.0,<0.10.0)`.

However the new version of `instructor` fixes this.

Thanks!
