### ISSUE TITLE
connecting to lmstudio vllm?

### ISSUE THREAD

**Issue by tendaysaweek** [joaomdmoura/crewAI#69]
Hi, 
would it be possible to add support for these or is it possible at the moment? 
I tried combing throught the code with success.

**Comment by TheBitmonkey** [comment]
try pop this at the top of your example... 

os.environ["OPENAI_API_BASE"]="http://localhost:1234/v1"

**Comment by tendaysaweek** [comment]
didn't even think that would so simple, thank you.
