### ISSUE TITLE
How can I specify to use GPT-3.5?

### ISSUE THREAD

**Issue by libertyteeth** [joaomdmoura/crewAI#73]
Running the example from the README cost 34 cents, using GPT-4.

Was wondering what the cost differential would be between GPT-3.5 and GPT-4, but I can't find where to put that in the code.

Thank you, for this tool and the support!  Feliz ano novo.  :)

**Comment by joaomdmoura** [comment]
Should be pretty straightforward:

```python
from langchain.chat_models import ChatOpenAI

gpt35 = ChatOpenAI(
  temperature=0.7,
  model_name="gpt-3.5",
)

Agent(
# ...
llm=gpt35
```

**Comment by Lachlan-White** [comment]
@joaomdmoura Running the above example Met with the below error: 

``openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-3.5` does not exist', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}``

**Comment by DonFelidae** [comment]
the same problem here:
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-3.5` does not exist', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

code:
llm=OpenAI(model_name="gpt-3.5", temperature=0.7)
