### ISSUE TITLE
ModuleNotFoundError: No module named 'crewai_tools'

### ISSUE THREAD

**Issue by Vigtu** [joaomdmoura/crewAI#740]
I created a new environment and ran pip install crewai and pip install 'crewai[tools]'. However, every time I run the code, I encounter the same error. I've tried reinstalling, creating another environment, and updating, but unfortunately, nothing works.

Traceback (most recent call last):
  File "c:\Users\VICTORCORREAGOMES\Documents\DataScienceMachineLearning\quizzLlhama\tempCodeRunnerFile.py", line 2, in <module>
    from crewai_tools import CSVSearchTool
ModuleNotFoundError: No module named 'crewai_tools'

my libs:
from crewai import Agent, Task, Crew, Process
from crewai_tools import CSVSearchTool
import os

via pip show crewai-tools / crewai:
CrewAI version:  0.30.11
CrewAI Tools Version: 0.2.6
Python Version: 3.12.3

pip list:
Package                                  Version
---------------------------------------- ---------------
aiohttp                                  3.9.5
aiosignal                                1.3.1
alembic                                  1.13.1
annotated-types                          0.7.0
anyio                                    4.4.0
appdirs                                  1.4.4
asgiref                                  3.8.1
attrs                                    23.2.0
backoff                                  2.2.1
bcrypt                                   4.1.3
beautifulsoup4                           4.12.3
boto3                                    1.34.121
botocore                                 1.34.121
Brotli                                   1.1.0
build                                    1.2.1
cachetools                               5.3.3
certifi                                  2024.6.2
cffi                                     1.16.0
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.3
chromadb                                 0.4.24
click                                    8.1.7
cohere                                   5.5.5
colorama                                 0.4.6
coloredlogs                              15.0.1
crewai                                   0.30.11
crewai-tools                             0.2.6
cryptography                             42.0.8
dataclasses-json                         0.6.6
decorator                                5.1.1
Deprecated                               1.2.14
deprecation                              2.1.0
distro                                   1.9.0
docstring-parser                         0.15
docx2txt                                 0.8
embedchain                               0.1.102
fastapi                                  0.110.3
fastavro                                 1.9.4
filelock                                 3.14.0
flatbuffers                              24.3.25
frozenlist                               1.4.1
fsspec                                   2024.6.0
gitdb                                    4.0.11
GitPython                                3.1.43
google-api-core                          2.19.0
google-auth                              2.30.0
google-cloud-aiplatform                  1.53.0
google-cloud-bigquery                    3.24.0
google-cloud-core                        2.4.1
google-cloud-resource-manager            1.12.3
google-cloud-storage                     2.16.0
google-crc32c                            1.5.0
google-resumable-media                   2.7.0
googleapis-common-protos                 1.63.1
gptcache                                 0.1.43
greenlet                                 3.0.3
grpc-google-iam-v1                       0.13.0
grpcio                                   1.64.1
grpcio-status                            1.62.2
h11                                      0.14.0
httpcore                                 1.0.5
httptools                                0.6.1
httpx                                    0.27.0
httpx-sse                                0.4.0
huggingface-hub                          0.23.3
humanfriendly                            10.0
idna                                     3.7
importlib_metadata                       7.1.0
importlib_resources                      6.4.0
iniconfig                                2.0.0
instructor                               0.5.2
jmespath                                 1.0.1
jsonpatch                                1.33
jsonpointer                              2.4
kubernetes                               30.1.0
lancedb                                  0.5.7
langchain                                0.1.20
langchain-cohere                         0.1.5
langchain-community                      0.0.38
langchain-core                           0.1.52
langchain-openai                         0.0.5
langchain-text-splitters                 0.0.2
langsmith                                0.1.75
Mako                                     1.3.5
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.21.3
mdurl                                    0.1.2
mmh3                                     4.1.0
monotonic                                1.6
mpmath                                   1.3.0
multidict                                6.0.5
mutagen                                  1.47.0
mypy-extensions                          1.0.0
nodeenv                                  1.9.1
numpy                                    1.26.4
oauthlib                                 3.2.2
onnxruntime                              1.18.0
openai                                   1.32.0
opentelemetry-api                        1.25.0
opentelemetry-exporter-otlp-proto-common 1.25.0
opentelemetry-exporter-otlp-proto-grpc   1.25.0
opentelemetry-exporter-otlp-proto-http   1.25.0
opentelemetry-instrumentation            0.46b0
opentelemetry-instrumentation-asgi       0.46b0
opentelemetry-instrumentation-fastapi    0.46b0
opentelemetry-proto                      1.25.0
opentelemetry-sdk                        1.25.0
opentelemetry-semantic-conventions       0.46b0
opentelemetry-util-http                  0.46b0
orjson                                   3.10.3
outcome                                  1.3.0.post0
overrides                                7.7.0
packaging                                23.2
pip                                      24.0
pluggy                                   1.5.0
posthog                                  3.5.0
proto-plus                               1.23.0
protobuf                                 4.25.3
pulsar-client                            3.5.0
py                                       1.11.0
pyarrow                                  16.1.0
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pycparser                                2.22
pycryptodomex                            3.20.0
pydantic                                 2.7.3
pydantic_core                            2.18.4
PyGithub                                 1.59.1
Pygments                                 2.18.0
PyJWT                                    2.8.0
pylance                                  0.9.18
PyNaCl                                   1.5.0
pypdf                                    3.17.4
PyPika                                   0.48.9
pyproject_hooks                          1.1.0
pyreadline3                              3.4.1
pyright                                  1.1.366
pysbd                                    0.3.4
PySocks                                  1.7.1
pytest                                   8.2.2
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
pytube                                   15.0.0
PyYAML                                   6.0.1
ratelimiter                              1.2.0.post0
regex                                    2023.12.25
requests                                 2.32.3
requests-oauthlib                        2.0.0
retry                                    0.9.2
rich                                     13.7.1
rsa                                      4.9
s3transfer                               0.10.1
schema                                   0.7.7
selenium                                 4.21.0
semver                                   3.0.2
setuptools                               70.0.0
shapely                                  2.0.4
six                                      1.16.0
smmap                                    5.0.1
sniffio                                  1.3.1
sortedcontainers                         2.4.0
soupsieve                                2.5
SQLAlchemy                               2.0.30
starlette                                0.37.2
sympy                                    1.12.1
tenacity                                 8.3.0
tiktoken                                 0.5.2
tokenizers                               0.15.2
tqdm                                     4.66.4
trio                                     0.25.1
trio-websocket                           0.11.1
typer                                    0.9.4
types-requests                           2.32.0.20240602
typing_extensions                        4.12.1
typing-inspect                           0.9.0
urllib3                                  2.2.1
uvicorn                                  0.30.1
watchfiles                               0.22.0
websocket-client                         1.8.0
websockets                               12.0
wrapt                                    1.16.0
wsproto                                  1.2.0
yarl                                     1.9.4
youtube-transcript-api                   0.6.2
yt-dlp                                   2023.12.30
zipp                                     3.19.2

**Comment by gadgethome** [comment]
Ideally you should be running it in an environment such as conda or poetry. Create an environment, do the installs again and then hopefully it should work.

**Comment by imnotdev25** [comment]
Try to downgrade python version to 3.11.

**Comment by alipschutzsecuritize** [comment]
i have instaled pyenv, downgrade to python 3.11 and still don't work.
Not sure what's wrong.
Can you please tell me if there is something wrong on my env?

`ariellipschutz@Ariels-Laptop CrewAI2 % pip --version
pip 22.3 from /Users/ariellipschutz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pip (python 3.11)
ariellipschutz@Ariels-Laptop CrewAI2 % /opt/homebrew/bin/python3 /Users/ariellipschutz/Projects/CrewAI2/crew_agent.py
/opt/homebrew/lib/python3.12/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/Users/ariellipschutz/Projects/CrewAI2/crew_agent.py", line 3, in <module>
    from crewai_tools import SerperDevTool
ModuleNotFoundError: No module named 'crewai_tools'
ariellipschutz@Ariels-Laptop CrewAI2 % `

Thanks
