### ISSUE TITLE
increase time for response || complex tasks.

### ISSUE THREAD

**Issue by tendaysaweek** [joaomdmoura/crewAI#75]
I've been testing more complex tasks and I see we get hang outs, has anyone tried changing the values in the code to allow longer conversations to occur? 

Note: Please make sure to include any code you used for your analysis in your report. Also, ensure that all information is accurate and up-to-date as per current knowledge and data available at the time of writing this response.Retrying langchain_community.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPConnectionPool(host='localhost', port=1250): Read timed out. (read timeout=600).

![image](https://github.com/joaomdmoura/crewAI/assets/69711075/e3ce7bff-0c91-4aa4-bf3d-42017fa3d604)

**Comment by joaomdmoura** [comment]
this is odd, afaik there is no time limitation on the execution this seems to be more related to higher latency on the http calls, is this still an issue? Closing it for now but happy to reopen

**Comment by tendaysaweek** [comment]
honestly kidna gave up on this, as it did reoccur.
I will try downloading the current version an give it a go.
