### ISSUE TITLE
ModuleNotFoundError: No module named 'crewai.agents.cache

### ISSUE THREAD

**Issue by tendaysaweek** [joaomdmoura/crewAI#76]
seems to be identified in vscode, running the code numerous times with different tasks worked.
then I tried agent_test.py and getting this, am I using something incorrectly?

**Comment by joaomdmoura** [comment]
@tendaysaweek just to sanity check, you got this error when running the `tests/agent_test.py` from this repo right?
What version of crewAI you have installed?

**Comment by tendaysaweek** [comment]
yes to the py, and pulled fresh version this morning.

**Comment by greysonlalonde** [comment]
Closing this in reference to https://github.com/joaomdmoura/crewAI/pull/99
