### ISSUE TITLE
ImportError: cannot import name 'SerperDevTool' from 'crewai_tools' 

### ISSUE THREAD

**Issue by kamalkech** [joaomdmoura/crewAI#762]
i follow ur official documentation here [https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/](https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/)
after run server get this error :
ImportError: cannot import name 'SerperDevTool' from 'crewai_tools'

**Comment by lorenzejay** [comment]
@kamalkech did you run 

`pip install 'crewai[tools]'`

**Comment by kamalkech** [comment]
@lorenzejay i already install  
```cmd
pip install crewai
pip install 'crewai[tools]'
```

but get this error 
```
 from crewai_tools import SerperDevTool
ImportError: cannot import name 'SerperDevTool' from 'crewai_tools'
```

**Comment by stephenkhoo** [comment]
Same issue, I'm on m1 macOS.

**Comment by kru2710shna** [comment]
->Did you also initialize tools like this  `serper_tool = SerperDevTool()` in code ?
-> Check under `pip list` on terminal 
-> pip install crewai==0.28.8 crewai_tools==0.1.6 langchain_community==0.0.29

Now it should work

**Comment by kru2710shna** [comment]
> sorry i switch to langchain because the community not reactive and too slow

Okay!! I just saw this randomly and had solution in my mind 🤟🏿

**Comment by BrightLabsAI** [comment]
If you copy/ paste from the tutorial, there is a typo.
change `SerpeDevTool` to `SerperDevTool`

This should work...

**Comment by gcpdev** [comment]
For anyone searching for a solution when facing this problem:

Double-check if you are not importing `crewai.tools` instead of `crewai_tools`. Both are accepted, which is a library issue that causes ambiguity, but the correct one is `crewai_tools`. If you used an LLM to generate your code, it will likely import the wrong one instead.

**Comment by amansingh9097** [comment]
@gcpdev I had `crewai_tools` in my code but still got the below error:
```
ImportError: cannot import name 'tool' from 'crewai_tools'. Did you mean: 'tools'?
```

So I switched to `crewai.tools` but now it says
```
ImportError: cannot import name 'SerperDevTool' from 'crewai.tools'
```

has anyone been able to use any proper web search tool with crewai? I often get issues with DuckDuckGo implementation with crewai as well

**Comment by MaryNfs** [comment]
[Not relevent to the issue]
> has anyone been able to use any proper web search tool with crewai? I often get issues with DuckDuckGo implementation with crewai as well

@amansingh9097 have you tried using `langchain_community.tools` module and a custom tool decorator from the `crewai.tools` module? 
Below worked for me:

```
from langchain_community.tools import DuckDuckGoSearchRun
from crewai.tools import tool

search_ddg_tool = DuckDuckGoSearchRun()

@tool('DuckDuckGoSearch')
def ddg_search(search_query: str):
    return search_ddg_tool.run(search_query)
```

**Comment by sanxore** [comment]
same issue

**Comment by Vidit-Ostwal** [comment]
I just tried with the latest version directly from the git, it works completely fine.
Attaching a successful import screenshot

<img width="851" alt="Image" src="https://github.com/user-attachments/assets/30da3afc-d900-4429-bb96-6a308887b483" />

**Comment by otakarkuchar** [comment]
same or me

**Comment by Naveenpandey27** [comment]
i am facing this issue 

`cannot import name 'WebsiteSearchTool' from 'crewai_tools' `

**Comment by spela** [comment]
From `pip list`:
```
crewai                                   0.159.0
crewai-tools                             0.0.1
```

```
Exception has occurred: ImportError
cannot import name 'SerperDevTool' from 'crewai_tools'
```

I'm unable to upgrade crewai-tools (with `pip install --upgrade crewai['tools']`) because it requires some older version of `tictoken` which fails to build.

Anyone?

BTW, why is this closed?
