### ISSUE TITLE
Dependency issue with FastAPI

### ISSUE THREAD

**Issue by ashokgit** [joaomdmoura/crewAI#784]
Hi, I got this issue on my installation with crewAI installation along with FastAPI  

`
Because no versions of crewai match >0.30.11,<0.31.0
 and crewai (0.30.11) depends on instructor (>=0.5.2,<0.6.0), crewai (>=0.30.11,<0.31.0) requires instructor (>=0.5.2,<0.6.0).
(1) So, because no versions of instructor match >0.5.2,<0.6.0
 and instructor (0.5.2) depends on typer (>=0.9.0,<0.10.0), crewai (>=0.30.11,<0.31.0) requires typer (>=0.9.0,<0.10.0).

    Because no versions of fastapi-cli match >0.0.2,<0.0.3 || >0.0.3,<0.0.4 || >0.0.4
 and fastapi-cli (0.0.2) depends on typer (>=0.12.3), fastapi-cli (>=0.0.2,<0.0.3 || >0.0.3,<0.0.4 || >0.0.4) requires typer (>=0.12.3).
    And because fastapi-cli (0.0.3) depends on typer (>=0.12.3)
 and fastapi-cli (0.0.4) depends on typer (>=0.12.3), fastapi-cli (>=0.0.2) requires typer (>=0.12.3).
    And because crewai (>=0.30.11,<0.31.0) requires typer (>=0.9.0,<0.10.0) (1), crewai (>=0.30.11,<0.31.0) is incompatible with fastapi-cli (>=0.0.2)
    And because fastapi (0.111.0) depends on fastapi-cli (>=0.0.2)
 and no versions of fastapi match >0.111.0,<0.112.0, crewai (>=0.30.11,<0.31.0) is incompatible with fastapi (>=0.111.0,<0.112.0).
    So, because cmx contact extraction depends on both fastapi (^0.111.0) and crewai (^0.30.11), version solving failed.
`

Breakdown of the Issue:
crewai (0.30.11) requires instructor (>=0.5.2,<0.6.0), which in turn requires typer (>=0.9.0,<0.10.0).
fastapi (0.111.0) depends on fastapi-cli (>=0.0.2), which requires typer (>=0.12.3).
This creates a conflict because crewai requires a version of typer that is lower than what fastapi-cli requires.

How can this be mitigated?

**Comment by ashokgit** [comment]
forget the above. poetry add git+https://github.com/joaomdmoura/crewAI.git worked

**Comment by weisisheng** [comment]
Hmm, i get the same error even with the new repo.
