### ISSUE TITLE
[Feature] Agent to automate task of daily social media posting on all social media plateforms, fetching data from the chatGPT prompt based fine tuning agent.

### ISSUE THREAD

**Issue by yasir23** [joaomdmoura/crewAI#84]
Basically I got the idea of making an agent like to help enterprise or any major business to automate the task of posting on social media on daily basis through agent.

Actually here the two agents will be working for the task to perform, one is for content fetching from prompt engineering for the perticuler niche of business and other will be posting on different social media handles with image and written posts.

**Comment by dirvine** [comment]
See langchain docs. It can be done with that integration easily

**Comment by joaomdmoura** [comment]
Hey there, it seems to be less of an issue of request for crewAI itself and more of something to build with it, I actually built a similar example in the examples repo: https://github.com/joaomdmoura/crewAI-examples/tree/main/instagram_post
