### ISSUE TITLE
Training agents: crewai train -n 5 gives an error 

### ISSUE THREAD

**Issue by ukpark** [joaomdmoura/crewAI#865]
When I run the command for training an agent. It gives a following error.

$ crewai train -n 5
Training the crew for 5 iterations
Command not found: train
An error occurred while training the crew: Command '['poetry', 'run', 'train', '5']' returned non-zero exit status 1.

Is there any way to debug?

**Comment by theCyberTech** [comment]
Can you post the following

Python version
Poetry version
CrewAI version (+ crewAI-tools)
A screenshot of the error (please include the crewai create command in the screenshot)

**Comment by ukpark** [comment]
The error came because I didn't create the project through 'crewai create'. 

Thank you! @theCyberTech 
I got the glue from your comment.

**Comment by sebastianserna-cbm** [comment]
What if I already have a project and I want to update it, so I can use the "train" command?
