### ISSUE TITLE
Issues with "chat with our docs" and "Join our Discord"

### ISSUE THREAD

**Issue by AlABarazi** [joaomdmoura/crewAI#915]
Hi, 
Maybe this is not the right place to post about these issue, but I could not find a place to post question or ask for help related to crewai.
on crewai.com both "chat with our docs"  and "Join our Discord" are not working for me.
<img width="1354" alt="Screenshot 2024-07-11 at 3 28 24 PM" src="https://github.com/joaomdmoura/crewAI/assets/7549404/ea7d04e5-7fd8-4dff-b5ce-c4153a76cfeb">
chat with our docs require that user   signup to chatgpt. I tried to login ...etc .. I could not
<img width="523" alt="Screenshot 2024-07-11 at 3 28 37 PM" src="https://github.com/joaomdmoura/crewAI/assets/7549404/ea671ec6-a7da-4688-af27-8a022e13a862">
Join our Discord show another problems
<img width="888" alt="Screenshot 2024-07-11 at 3 29 27 PM" src="https://github.com/joaomdmoura/crewAI/assets/7549404/005d41ad-6d80-4493-9ccd-5c2c5fd18cc8">

I wonder what are the channels to reach out for help? And why the site is having links that are not working ?

**Comment by theCyberTech** [comment]
can you PM me your username on Discord and I will send you what's up, Im the discord moderator. Also what does that message say??

**Comment by theCyberTech** [comment]
Sign ing to chatgpt will eb outside of our control Im afraid

**Comment by theCyberTech** [comment]
Interesting not sure what's happening but it look like you need a plus account which is weird, you might need to reach out to chatgpt support as we have no control over that side of thing, in the mean time feel free to PM on discord: .riptear

**Comment by theCyberTech** [comment]
![CleanShot 2024-07-11 at 22 24 35@2x](https://github.com/joaomdmoura/crewAI/assets/84775494/bf675914-b857-4f36-80e4-d92332122235)
Can you click on the arrow next to the welcome name to expand the channel group so you can see the rules channel to bel Abel to accept them

**Comment by AlABarazi** [comment]
Thanks it is working now!
