### ISSUE TITLE
[Feature Request] Adding a "Ask Human" Agent class

### ISSUE THREAD

**Issue by tituslhy** [joaomdmoura/crewAI#921]
There are increasingly more agentic systems with human-in-the-loop capabilities and I was following this thread (https://github.com/joaomdmoura/crewAI/issues/258) with interest. May I suggest creating an "AskHuman" agent abstraction? That way in a hierarchical crew (or any crew) the manager/respective agents can seek further clarification from the human user. 

I understand that crewAI is built on top of langchain and langgraph has recently released human-in-the-loop capabilities (https://langchain-ai.github.io/langgraph/how-tos/human_in_the_loop/wait-user-input/#agent). Alternatively, an example implementation using crewAI with langgraph's latest functionalities is great as well! Always looking forward to learn.

**Comment by tituslhy** [comment]
Sorry I just realized it's implemented as a flag. Closing the issue 

https://docs.crewai.com/how-to/Human-Input-on-Execution/

**Comment by jakin6** [comment]
Hello, help me to handle the human in loop on ui , so that it can be easy to integrate with any frontend framewwork or mobile app
