### ISSUE TITLE
\nObservation:.... included in tool input

### ISSUE THREAD

**Issue by chartstudy** [joaomdmoura/crewAI#96]
It's getting an llm response that looks like this:

Thought: Do I need to use a tool? Yes
Action: get_webpage_content
Action Input: https://khanacademy.org/giraffes
Observation: [Awaiting input to proceed]

And it's calling my get_webpage_content tool with: "'https://khanacademy.org/giraffes\nObservation: [Awaiting input to proceed]'"

**Comment by joaomdmoura** [comment]
Weird, what is the llm you are using? Is this still happening, I'm assuming this is an open source model, I think the new version of crewAI should have fixed this, if not you could add `Observation` as a stop word for the model, but ideally that wouldn't be necessary. I'm closing for now but lmk if it's still happening and I'll reopen it
